// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> setIntegerFpsMode({required bool enabled}) =>
    RustLib.instance.api.crateApiEmulationSetIntegerFpsMode(enabled: enabled);

Future<void> saveState({required String path}) =>
    RustLib.instance.api.crateApiEmulationSaveState(path: path);

Future<void> loadState({required String path}) =>
    RustLib.instance.api.crateApiEmulationLoadState(path: path);

Future<Uint8List> saveStateToMemory() =>
    RustLib.instance.api.crateApiEmulationSaveStateToMemory();

Future<void> loadStateFromMemory({required List<int> data}) =>
    RustLib.instance.api.crateApiEmulationLoadStateFromMemory(data: data);
