// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Seeks to a specific frame in the rewind history for the History Viewer.
///
/// `position` is 0-indexed, where 0 is the oldest frame and `frame_count - 1` is the newest.
/// After calling this, subscribe to `history_state_stream` in `events.rs` to receive updates.
Future<void> historySeek({required BigInt position}) =>
    RustLib.instance.api.crateApiHistoryHistorySeek(position: position);

Future<void> historyApply({required BigInt position}) =>
    RustLib.instance.api.crateApiHistoryHistoryApply(position: position);
