// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `set_gamepad_masks`, `update_runtime_input`

Future<void> setPadMask({required int pad, required int mask}) =>
    RustLib.instance.api.crateApiInputSetPadMask(pad: pad, mask: mask);

Future<void> setTurboMask({required int pad, required int mask}) =>
    RustLib.instance.api.crateApiInputSetTurboMask(pad: pad, mask: mask);

Future<void> setTurboFramesPerToggle({required int frames}) =>
    RustLib.instance.api.crateApiInputSetTurboFramesPerToggle(frames: frames);

Future<void> setTurboTiming({required int onFrames, required int offFrames}) =>
    RustLib.instance.api.crateApiInputSetTurboTiming(
      onFrames: onFrames,
      offFrames: offFrames,
    );
