// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Future<void> startNesRuntime() =>
    RustLib.instance.api.crateApiLoadRomStartNesRuntime();

Future<void> loadRom({required String path}) =>
    RustLib.instance.api.crateApiLoadRomLoadRom(path: path);

Future<void> loadRomFromBytes({required List<int> bytes}) =>
    RustLib.instance.api.crateApiLoadRomLoadRomFromBytes(bytes: bytes);

Future<void> resetConsole() =>
    RustLib.instance.api.crateApiLoadRomResetConsole();

Future<void> powerResetConsole() =>
    RustLib.instance.api.crateApiLoadRomPowerResetConsole();

Future<void> powerOffConsole() =>
    RustLib.instance.api.crateApiLoadRomPowerOffConsole();

Future<Uint8List?> getRomHash() =>
    RustLib.instance.api.crateApiLoadRomGetRomHash();
