// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Get all local IPv4 and IPv6 addresses.
Future<List<String>> getLocalAddrs() =>
    RustLib.instance.api.crateApiNetUtilsGetLocalAddrs();

/// Try to get the public IP address using an HTTP service.
Future<String?> getPublicIp() =>
    RustLib.instance.api.crateApiNetUtilsGetPublicIp();

/// Try to map a port using UPnP.
/// TODO: Implement actual UPnP port mapping.
Future<void> tryUpnpMapping({required int port, required String labelPrefix}) =>
    RustLib.instance.api.crateApiNetUtilsTryUpnpMapping(
      port: port,
      labelPrefix: labelPrefix,
    );
