// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `from`, `from`

Future<List<PalettePresetInfo>> palettePresets() =>
    RustLib.instance.api.crateApiPalettePalettePresets();

Future<void> setPalettePreset({required PaletteKind kind}) =>
    RustLib.instance.api.crateApiPaletteSetPalettePreset(kind: kind);

Future<void> setPalettePalData({required List<int> data}) =>
    RustLib.instance.api.crateApiPaletteSetPalettePalData(data: data);

enum PaletteKind {
  nesdevNtsc,
  fbxCompositeDirect,
  sonyCxa2025AsUs,
  pal2C07,
  rawLinear,
}

class PalettePresetInfo {
  final PaletteKind kind;
  final String description;

  const PalettePresetInfo({required this.kind, required this.description});

  @override
  int get hashCode => kind.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PalettePresetInfo &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          description == other.description;
}
