// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_palette_kind`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

Future<List<PalettePresetInfo>> palettePresets() =>
    RustLib.instance.api.crateApiPalettePalettePresets();

Future<void> setPalettePreset({required String id}) =>
    RustLib.instance.api.crateApiPaletteSetPalettePreset(id: id);

Future<void> setPalettePalData({required List<int> data}) =>
    RustLib.instance.api.crateApiPaletteSetPalettePalData(data: data);

class PalettePresetInfo {
  final String id;
  final String description;

  const PalettePresetInfo({required this.id, required this.description});

  @override
  int get hashCode => id.hashCode ^ description.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PalettePresetInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          description == other.description;
}
