// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_server`, `is_running`, `new`, `notify_server_status`
// These types are ignored because they are neither used by any `pub` functions nor (for structs and enums) marked `#[frb(unignore)]`: `EmbeddedServer`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

/// Start the embedded netplay server on the specified port.
///
/// Pass `port = 0` to let the OS pick an available port.
Future<int> netserverStart({required int port}) =>
    RustLib.instance.api.crateApiServerNetserverStart(port: port);

/// Stop the embedded netplay server.
Future<void> netserverStop() =>
    RustLib.instance.api.crateApiServerNetserverStop();

/// Check if the embedded server is currently running.
Future<bool> netserverIsRunning() =>
    RustLib.instance.api.crateApiServerNetserverIsRunning();

/// Get the current server port (0 if not running).
Future<int> netserverGetPort() =>
    RustLib.instance.api.crateApiServerNetserverGetPort();

/// Subscribe to server status updates.
Stream<ServerStatus> netserverStatusStream() =>
    RustLib.instance.api.crateApiServerNetserverStatusStream();

/// Server status snapshot streamed to Flutter.
class ServerStatus {
  final bool running;
  final int port;
  final int clientCount;
  final String bindAddress;

  const ServerStatus({
    required this.running,
    required this.port,
    required this.clientCount,
    required this.bindAddress,
  });

  @override
  int get hashCode =>
      running.hashCode ^
      port.hashCode ^
      clientCount.hashCode ^
      bindAddress.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerStatus &&
          runtimeType == other.runtimeType &&
          running == other.running &&
          port == other.port &&
          clientCount == other.clientCount &&
          bindAddress == other.bindAddress;
}
