/// NES 2.0: interpreted default expansion device (header byte 15).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Nes2DefaultExpansionDevice {
    Unspecified,
    StandardControllers,
    FourScoreOrSatelliteTwoExtraControllers,
    FamicomFourPlayersAdapterSimpleProtocol,
    VsSystem4016,
    VsSystem4017,
    Reserved,
    VsZapper,
    Zapper4017,
    TwoZappers,
    BandaiHyperShotLightgun,
    PowerPadSideA,
    PowerPadSideB,
    FamilyTrainerSideA,
    FamilyTrainerSideB,
    ArkanoidVausControllerNes,
    ArkanoidVausControllerFamicom,
    TwoVausControllersPlusFamicomDataRecorder,
    KonamiHyperShot,
    CoconutsPachinko,
    ExcitingBoxingPunchingBag,
    JissenMahjong,
    PartyTap,
    OekaKidsTablet,
    SunsoftBarcodeBattler,
    MiraclePianoKeyboard,
    PokkunMoguraaTapTapMat,
    TopRider,
    DoubleFisted,
    Famicom3dSystem,
    DoremikkoKeyboard,
    RobGyromite,
    FamicomDataRecorderSilentKeyboard,
    AsciiTurboFile,
    IgsBattleBox,
    FamilyBasicKeyboardPlusDataRecorder,
    PecKeyboard,
    Bit79Keyboard,
    SuborKeyboard,
    SuborKeyboardPlusMacroWinnersMouse,
    SuborKeyboardPlusSuborMouse4016,
    SnesMouse4016,
    Multicart,
    TwoSnesControllersReplacingStandard,
    RacerMateBicycle,
    UForce,
    RobStackUp,
    CityPatrolmanLightgun,
    SharpC1CassetteInterface,
    StandardControllerSwappedDirectionsAndBA,
    ExcaliburSudokuPad,
    AblPinball,
    GoldenNuggetCasinoExtraButtons,
    KedaKeyboard,
    SuborKeyboardPlusSuborMouse4017,
    PortTestController,
    BandaiMultiGamePlayerGamepadButtons,
    VenomTvDanceMat,
    LgTvRemoteControl,
    FamicomNetworkController,
    KingFishingController,
    CroakyKaraokeController,
    KingwonKeyboard,
    ZechengKeyboard,
    SuborKeyboardPlusL90RotatedPs2Mouse4017,
    Ps2KeyboardUm6578PortPlusPs2Mouse4017,
    Ps2MouseUm6578Port,
    YuxingMouse4016,
    SuborKeyboardPlusYuxingMouse4016,
    GigggleTvPump,
    BbkKeyboardPlusR90RotatedPs2Mouse4017,
    MagicalCooking,
    SnesMouse4017,
    Zapper4016,
    ArkanoidVausControllerPrototype,
    TvMahjongGameController,
    MahjongGekitouDensetsuController,
    SuborKeyboardPlusXInvertedPs2Mouse4017,
    IbmPcXtKeyboard,
    SuborKeyboardPlusMegaBookMouse,
    Unknown(u8),
}

impl Nes2DefaultExpansionDevice {
    pub fn from_id(id: u8) -> Self {
        match id {
            0x00 => Self::Unspecified,
            0x01 => Self::StandardControllers,
            0x02 => Self::FourScoreOrSatelliteTwoExtraControllers,
            0x03 => Self::FamicomFourPlayersAdapterSimpleProtocol,
            0x04 => Self::VsSystem4016,
            0x05 => Self::VsSystem4017,
            0x06 => Self::Reserved,
            0x07 => Self::VsZapper,
            0x08 => Self::Zapper4017,
            0x09 => Self::TwoZappers,
            0x0A => Self::BandaiHyperShotLightgun,
            0x0B => Self::PowerPadSideA,
            0x0C => Self::PowerPadSideB,
            0x0D => Self::FamilyTrainerSideA,
            0x0E => Self::FamilyTrainerSideB,
            0x0F => Self::ArkanoidVausControllerNes,
            0x10 => Self::ArkanoidVausControllerFamicom,
            0x11 => Self::TwoVausControllersPlusFamicomDataRecorder,
            0x12 => Self::KonamiHyperShot,
            0x13 => Self::CoconutsPachinko,
            0x14 => Self::ExcitingBoxingPunchingBag,
            0x15 => Self::JissenMahjong,
            0x16 => Self::PartyTap,
            0x17 => Self::OekaKidsTablet,
            0x18 => Self::SunsoftBarcodeBattler,
            0x19 => Self::MiraclePianoKeyboard,
            0x1A => Self::PokkunMoguraaTapTapMat,
            0x1B => Self::TopRider,
            0x1C => Self::DoubleFisted,
            0x1D => Self::Famicom3dSystem,
            0x1E => Self::DoremikkoKeyboard,
            0x1F => Self::RobGyromite,
            0x20 => Self::FamicomDataRecorderSilentKeyboard,
            0x21 => Self::AsciiTurboFile,
            0x22 => Self::IgsBattleBox,
            0x23 => Self::FamilyBasicKeyboardPlusDataRecorder,
            0x24 => Self::PecKeyboard,
            0x25 => Self::Bit79Keyboard,
            0x26 => Self::SuborKeyboard,
            0x27 => Self::SuborKeyboardPlusMacroWinnersMouse,
            0x28 => Self::SuborKeyboardPlusSuborMouse4016,
            0x29 => Self::SnesMouse4016,
            0x2A => Self::Multicart,
            0x2B => Self::TwoSnesControllersReplacingStandard,
            0x2C => Self::RacerMateBicycle,
            0x2D => Self::UForce,
            0x2E => Self::RobStackUp,
            0x2F => Self::CityPatrolmanLightgun,
            0x30 => Self::SharpC1CassetteInterface,
            0x31 => Self::StandardControllerSwappedDirectionsAndBA,
            0x32 => Self::ExcaliburSudokuPad,
            0x33 => Self::AblPinball,
            0x34 => Self::GoldenNuggetCasinoExtraButtons,
            0x35 => Self::KedaKeyboard,
            0x36 => Self::SuborKeyboardPlusSuborMouse4017,
            0x37 => Self::PortTestController,
            0x38 => Self::BandaiMultiGamePlayerGamepadButtons,
            0x39 => Self::VenomTvDanceMat,
            0x3A => Self::LgTvRemoteControl,
            0x3B => Self::FamicomNetworkController,
            0x3C => Self::KingFishingController,
            0x3D => Self::CroakyKaraokeController,
            0x3E => Self::KingwonKeyboard,
            0x3F => Self::ZechengKeyboard,
            0x40 => Self::SuborKeyboardPlusL90RotatedPs2Mouse4017,
            0x41 => Self::Ps2KeyboardUm6578PortPlusPs2Mouse4017,
            0x42 => Self::Ps2MouseUm6578Port,
            0x43 => Self::YuxingMouse4016,
            0x44 => Self::SuborKeyboardPlusYuxingMouse4016,
            0x45 => Self::GigggleTvPump,
            0x46 => Self::BbkKeyboardPlusR90RotatedPs2Mouse4017,
            0x47 => Self::MagicalCooking,
            0x48 => Self::SnesMouse4017,
            0x49 => Self::Zapper4016,
            0x4A => Self::ArkanoidVausControllerPrototype,
            0x4B => Self::TvMahjongGameController,
            0x4C => Self::MahjongGekitouDensetsuController,
            0x4D => Self::SuborKeyboardPlusXInvertedPs2Mouse4017,
            0x4E => Self::IbmPcXtKeyboard,
            0x4F => Self::SuborKeyboardPlusMegaBookMouse,
            other => Self::Unknown(other),
        }
    }
}
