// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/emulation.dart';
import 'api/events.dart';
import 'api/gamepad.dart';
import 'api/input.dart';
import 'api/load_rom.dart';
import 'api/netplay.dart';
import 'api/palette.dart';
import 'api/pause.dart';
import 'api/server.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';
import 'senders/replay.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<DebugStateNotification>
  dco_decode_StreamSink_debug_state_notification_Sse(dynamic raw);

  @protected
  RustStreamSink<EmulationStatusNotification>
  dco_decode_StreamSink_emulation_status_notification_Sse(dynamic raw);

  @protected
  RustStreamSink<NetplayGameEvent> dco_decode_StreamSink_netplay_game_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<NetplayStatus> dco_decode_StreamSink_netplay_status_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<PaletteSnapshot> dco_decode_StreamSink_palette_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<ReplayEventNotification>
  dco_decode_StreamSink_replay_event_notification_Sse(dynamic raw);

  @protected
  RustStreamSink<RuntimeNotification>
  dco_decode_StreamSink_runtime_notification_Sse(dynamic raw);

  @protected
  RustStreamSink<ServerStatus> dco_decode_StreamSink_server_status_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<SpriteSnapshot> dco_decode_StreamSink_sprite_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TileSnapshot> dco_decode_StreamSink_tile_snapshot_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<TilemapSnapshot> dco_decode_StreamSink_tilemap_snapshot_Sse(
    dynamic raw,
  );

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuxTextureIds dco_decode_aux_texture_ids(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  GamepadButtonFfi dco_decode_box_autoadd_gamepad_button_ffi(dynamic raw);

  @protected
  GamepadMappingFfi dco_decode_box_autoadd_gamepad_mapping_ffi(dynamic raw);

  @protected
  int dco_decode_box_autoadd_u_8(dynamic raw);

  @protected
  DebugStateNotification dco_decode_debug_state_notification(dynamic raw);

  @protected
  EmulationStatusNotification dco_decode_emulation_status_notification(
    dynamic raw,
  );

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  GamepadActionsFfi dco_decode_gamepad_actions_ffi(dynamic raw);

  @protected
  GamepadButtonFfi dco_decode_gamepad_button_ffi(dynamic raw);

  @protected
  GamepadInfoFfi dco_decode_gamepad_info_ffi(dynamic raw);

  @protected
  GamepadMappingFfi dco_decode_gamepad_mapping_ffi(dynamic raw);

  @protected
  GamepadPollResultFfi dco_decode_gamepad_poll_result_ffi(dynamic raw);

  @protected
  int dco_decode_i_16(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<GamepadButtonFfi> dco_decode_list_gamepad_button_ffi(dynamic raw);

  @protected
  List<GamepadInfoFfi> dco_decode_list_gamepad_info_ffi(dynamic raw);

  @protected
  List<NetplayPlayer> dco_decode_list_netplay_player(dynamic raw);

  @protected
  List<PalettePresetInfo> dco_decode_list_palette_preset_info(dynamic raw);

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<SpriteInfo> dco_decode_list_sprite_info(dynamic raw);

  @protected
  NetplayGameEvent dco_decode_netplay_game_event(dynamic raw);

  @protected
  NetplayPlayer dco_decode_netplay_player(dynamic raw);

  @protected
  NetplayState dco_decode_netplay_state(dynamic raw);

  @protected
  NetplayStatus dco_decode_netplay_status(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  GamepadButtonFfi? dco_decode_opt_box_autoadd_gamepad_button_ffi(dynamic raw);

  @protected
  int? dco_decode_opt_box_autoadd_u_8(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PaletteKind dco_decode_palette_kind(dynamic raw);

  @protected
  PalettePresetInfo dco_decode_palette_preset_info(dynamic raw);

  @protected
  PaletteSnapshot dco_decode_palette_snapshot(dynamic raw);

  @protected
  ReplayEventNotification dco_decode_replay_event_notification(dynamic raw);

  @protected
  RuntimeNotification dco_decode_runtime_notification(dynamic raw);

  @protected
  RuntimeNotificationKind dco_decode_runtime_notification_kind(dynamic raw);

  @protected
  ServerStatus dco_decode_server_status(dynamic raw);

  @protected
  SpriteInfo dco_decode_sprite_info(dynamic raw);

  @protected
  SpriteSnapshot dco_decode_sprite_snapshot(dynamic raw);

  @protected
  TileSnapshot dco_decode_tile_snapshot(dynamic raw);

  @protected
  TilemapMirroring dco_decode_tilemap_mirroring(dynamic raw);

  @protected
  TilemapSnapshot dco_decode_tilemap_snapshot(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<DebugStateNotification>
  sse_decode_StreamSink_debug_state_notification_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<EmulationStatusNotification>
  sse_decode_StreamSink_emulation_status_notification_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetplayGameEvent> sse_decode_StreamSink_netplay_game_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<NetplayStatus> sse_decode_StreamSink_netplay_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<PaletteSnapshot> sse_decode_StreamSink_palette_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<ReplayEventNotification>
  sse_decode_StreamSink_replay_event_notification_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<RuntimeNotification>
  sse_decode_StreamSink_runtime_notification_Sse(SseDeserializer deserializer);

  @protected
  RustStreamSink<ServerStatus> sse_decode_StreamSink_server_status_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<SpriteSnapshot> sse_decode_StreamSink_sprite_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TileSnapshot> sse_decode_StreamSink_tile_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<TilemapSnapshot> sse_decode_StreamSink_tilemap_snapshot_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuxTextureIds sse_decode_aux_texture_ids(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  GamepadButtonFfi sse_decode_box_autoadd_gamepad_button_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GamepadMappingFfi sse_decode_box_autoadd_gamepad_mapping_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  DebugStateNotification sse_decode_debug_state_notification(
    SseDeserializer deserializer,
  );

  @protected
  EmulationStatusNotification sse_decode_emulation_status_notification(
    SseDeserializer deserializer,
  );

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  GamepadActionsFfi sse_decode_gamepad_actions_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GamepadButtonFfi sse_decode_gamepad_button_ffi(SseDeserializer deserializer);

  @protected
  GamepadInfoFfi sse_decode_gamepad_info_ffi(SseDeserializer deserializer);

  @protected
  GamepadMappingFfi sse_decode_gamepad_mapping_ffi(
    SseDeserializer deserializer,
  );

  @protected
  GamepadPollResultFfi sse_decode_gamepad_poll_result_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_16(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<GamepadButtonFfi> sse_decode_list_gamepad_button_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<GamepadInfoFfi> sse_decode_list_gamepad_info_ffi(
    SseDeserializer deserializer,
  );

  @protected
  List<NetplayPlayer> sse_decode_list_netplay_player(
    SseDeserializer deserializer,
  );

  @protected
  List<PalettePresetInfo> sse_decode_list_palette_preset_info(
    SseDeserializer deserializer,
  );

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<SpriteInfo> sse_decode_list_sprite_info(SseDeserializer deserializer);

  @protected
  NetplayGameEvent sse_decode_netplay_game_event(SseDeserializer deserializer);

  @protected
  NetplayPlayer sse_decode_netplay_player(SseDeserializer deserializer);

  @protected
  NetplayState sse_decode_netplay_state(SseDeserializer deserializer);

  @protected
  NetplayStatus sse_decode_netplay_status(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  GamepadButtonFfi? sse_decode_opt_box_autoadd_gamepad_button_ffi(
    SseDeserializer deserializer,
  );

  @protected
  int? sse_decode_opt_box_autoadd_u_8(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PaletteKind sse_decode_palette_kind(SseDeserializer deserializer);

  @protected
  PalettePresetInfo sse_decode_palette_preset_info(
    SseDeserializer deserializer,
  );

  @protected
  PaletteSnapshot sse_decode_palette_snapshot(SseDeserializer deserializer);

  @protected
  ReplayEventNotification sse_decode_replay_event_notification(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeNotification sse_decode_runtime_notification(
    SseDeserializer deserializer,
  );

  @protected
  RuntimeNotificationKind sse_decode_runtime_notification_kind(
    SseDeserializer deserializer,
  );

  @protected
  ServerStatus sse_decode_server_status(SseDeserializer deserializer);

  @protected
  SpriteInfo sse_decode_sprite_info(SseDeserializer deserializer);

  @protected
  SpriteSnapshot sse_decode_sprite_snapshot(SseDeserializer deserializer);

  @protected
  TileSnapshot sse_decode_tile_snapshot(SseDeserializer deserializer);

  @protected
  TilemapMirroring sse_decode_tilemap_mirroring(SseDeserializer deserializer);

  @protected
  TilemapSnapshot sse_decode_tilemap_snapshot(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_debug_state_notification_Sse(
    RustStreamSink<DebugStateNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_emulation_status_notification_Sse(
    RustStreamSink<EmulationStatusNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_netplay_game_event_Sse(
    RustStreamSink<NetplayGameEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_netplay_status_Sse(
    RustStreamSink<NetplayStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_palette_snapshot_Sse(
    RustStreamSink<PaletteSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_replay_event_notification_Sse(
    RustStreamSink<ReplayEventNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_runtime_notification_Sse(
    RustStreamSink<RuntimeNotification> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_server_status_Sse(
    RustStreamSink<ServerStatus> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_sprite_snapshot_Sse(
    RustStreamSink<SpriteSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tile_snapshot_Sse(
    RustStreamSink<TileSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_tilemap_snapshot_Sse(
    RustStreamSink<TilemapSnapshot> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_aux_texture_ids(AuxTextureIds self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_gamepad_button_ffi(
    GamepadButtonFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_gamepad_mapping_ffi(
    GamepadMappingFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_debug_state_notification(
    DebugStateNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_emulation_status_notification(
    EmulationStatusNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_gamepad_actions_ffi(
    GamepadActionsFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gamepad_button_ffi(
    GamepadButtonFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gamepad_info_ffi(
    GamepadInfoFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gamepad_mapping_ffi(
    GamepadMappingFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_gamepad_poll_result_ffi(
    GamepadPollResultFfi self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_gamepad_button_ffi(
    List<GamepadButtonFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_gamepad_info_ffi(
    List<GamepadInfoFfi> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_netplay_player(
    List<NetplayPlayer> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_palette_preset_info(
    List<PalettePresetInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_loose(List<int> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_sprite_info(
    List<SpriteInfo> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_netplay_game_event(
    NetplayGameEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_netplay_player(NetplayPlayer self, SseSerializer serializer);

  @protected
  void sse_encode_netplay_state(NetplayState self, SseSerializer serializer);

  @protected
  void sse_encode_netplay_status(NetplayStatus self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_gamepad_button_ffi(
    GamepadButtonFfi? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_8(int? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
    Uint8List? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_palette_kind(PaletteKind self, SseSerializer serializer);

  @protected
  void sse_encode_palette_preset_info(
    PalettePresetInfo self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_palette_snapshot(
    PaletteSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_replay_event_notification(
    ReplayEventNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_notification(
    RuntimeNotification self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_runtime_notification_kind(
    RuntimeNotificationKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_server_status(ServerStatus self, SseSerializer serializer);

  @protected
  void sse_encode_sprite_info(SpriteInfo self, SseSerializer serializer);

  @protected
  void sse_encode_sprite_snapshot(
    SpriteSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tile_snapshot(TileSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_tilemap_mirroring(
    TilemapMirroring self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_tilemap_snapshot(
    TilemapSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
