use bitflags::bitflags;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum IrqKind {
    Nmi,
    Irq,
}

bitflags! {
    /// A bitmask of **hardware sources** that can assert the CPU's **IRQ** line.
    ///
    /// On the NES family, many independent devices can request an interrupt.
    /// Emulators often model this as a set of flags so multiple sources can be
    /// pending at once (e.g. DMC + APU frame counter).
    ///
    /// This mirrors Mesen2's `IRQSource` bit assignments:
    /// External(1), FrameCounter(2), DMC(4), FdsDisk(8), Epsm(16).
    #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
    pub struct IrqSource: u8 {
        /// **External / Mapper IRQ**
        ///
        /// IRQs generated by the cartridge/mapper hardware (e.g. scanline counters,
        /// CPU-cycle timers, or other board logic), and any other "external to the
        /// CPU/APU/PPU" interrupt sources exposed via the cartridge interface.
        ///
        /// Examples:
        /// - MMC3 scanline IRQ counter
        /// - VRC IRQ timers
        /// - Various homebrew/custom mapper IRQs
        const EXTERNAL = 0b0000_0001;

        /// **APU Frame Counter IRQ**
        ///
        /// The APU (Audio Processing Unit) includes a frame counter that clocks
        /// envelopes/length counters at fixed intervals. In 4-step mode (when
        /// IRQs are enabled), it can raise an IRQ periodically.
        ///
        /// Notes:
        /// - This is sometimes used by games for timing (audio updates, pacing).
        /// - It can be disabled via the frame counter control register.
        const FRAME_COUNTER = 0b0000_0010;

        /// **APU DMC IRQ**
        ///
        /// The DMC (Delta Modulation Channel) is the NES's sample playback unit.
        /// When DMC IRQ is enabled and the sample buffer runs out (i.e. it reaches
        /// the end of the sample and is not looping), it can request an IRQ.
        ///
        /// Notes:
        /// - Games may use this for streamed audio or timing.
        /// - The IRQ behavior depends on DMC loop/IRQ enable settings.
        const DMC = 0b0000_0100;

        /// **FDS Disk IRQ** (Famicom Disk System)
        ///
        /// The Famicom Disk System includes additional hardware (disk controller/
        /// BIOS-side logic) that can generate IRQs, typically for disk I/O and
        /// related timing events.
        ///
        /// Only relevant if you emulate FDS.
        const FDS_DISK = 0b0000_1000;

        /// **EPSM IRQ** (Yamaha-style expansion audio / FM)
        ///
        /// Some expansions (not part of the base NES) add extra sound hardware.
        /// "EPSM" refers to an extended sound module used in certain enhanced/
        /// homebrew/expansion contexts, which may have its own IRQ behavior.
        ///
        /// Only relevant if you support that expansion.
        const EPSM = 0b0001_0000;
    }
}
